sonar.projectKey=focalboard
sonar.projectName=Focalboard
sonar.sourceEncoding=UTF-8
sonar.sources=server,webapp/src,import
sonar.tests=server,webapp/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.test.js,**/*.test.jsx,**/*_test.go,**/*test.go,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=webapp/cypress/**,webapp/pack/**,**/node_modules/**,**/dist/**,**/bin/**,**/*.generated.*
sonar.coverage.exclusions=webapp/cypress/**,**/*.test.*,**/*_test.go,**/test/**,**/mocks/**
sonar.go.coverage.reportPaths=server/coverage.out
sonar.javascript.lcov.reportPaths=webapp/coverage/lcov.info
