sonar.projectKey=focalboard-server
sonar.projectName=Focalboard Server
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/assets/**,**/bin/**,**/dist/**,**/node_modules/**,**/swagger/clients/**,**/vendor/**
sonar.coverage.exclusions=**/*_test.go,**/mocks/**
sonar.go.coverage.reportPaths=coverage.out
