sonar.projectKey=focalboard-webapp
sonar.projectName=Focalboard Webapp
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src,cypress
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.test.js,src/**/*.test.jsx,cypress/**/*.ts,cypress/**/*.js
sonar.exclusions=coverage/**,pack/**,static/**,node_modules/**,__mocks__/**,cypress/screenshots/**,cypress/videos/**
sonar.coverage.exclusions=src/**/*.test.*,cypress/**,__mocks__/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
